### ISSUE TITLE
Schematic with WROOM-1 module

### ISSUE THREAD

**Issue by lecrams** [Xinyuan-LilyGO/LilyGo-Camera-Series#13]
Hi, I recently purchased the LilyGo ESP32 T-Camera S3 with OV2640 and pir.  On the board it states V1.6. However checking the V1.6 schematic shows a wrover module while my board is equipped with a WROOM-1 module!
according to the datasheets The pinning of the TROVER is different as the WROOM-1

Do you have a schematic available of the V1.6 HW with WROOM-1 module? That would allow me to develop my own code.
An pin assignment of which pins of ov2640 are conencted to which pins on WROOM-1 is also fine

**Comment by lbuque** [comment]
@lecrams If you are using T-Camera S3, you should get support at https://github.com/Xinyuan-LilyGO/LilyGo-Cam-ESP32S3.
