### ISSUE TITLE
T-Camera v162 on battery?

### ISSUE THREAD

**Issue by tomtobback** [Xinyuan-LilyGO/LilyGo-Camera-Series#14]
I have a T-Camera v1.6.2 which works well with esphome when powered by USB. however, when i connect a Li battery on the PH connector, the 3V3 line does not get any voltage. i looked at the [schematic](https://github.com/Xinyuan-LilyGO/LilyGo-Camera-Series/blob/master/schematic/T_CameraV162_Schematic.pdf) and i cannot find any trace from VBAT to the DC/DC or LDO. it seems to use the charger IC (IP5306) to boost VBAT to 5V, but i only get 2.0-2.2V on pin8 of that IC (VOUT connected to 5V). how can i make this work?

**Comment by JunliangYe** [comment]
I managed to boot up by pressing the rst button

**Comment by tomtobback** [comment]
thanks @JunliangYe you're right, i guess i did not press hard enough.
it draws about 150mA running esphome, not very battery friendly. any advice on how to hack v1.6.2 to get the PIR connected to an external wake-up pin?
