### ISSUE TITLE
Getting Started and Default Sketch

### ISSUE THREAD

**Issue by JpEncausse** [Xinyuan-LilyGO/LilyGo-Camera-Series#15]
Hello,

I have this camera board V1.7
https://fr.aliexpress.com/item/32968683765.html

- I'm looking for a getting started with Arduino IDE , what is the board configurtation and dependances
- The default code is very interesting using Display + PIR + Sound + Camera where can I find the code ? 

Many many thanks !

**Comment by lewisxhe** [comment]
You seem to have solved the problem, right? If you still have problems, please restart
