### ISSUE TITLE
can't upload on Arduino IDE

### ISSUE THREAD

**Issue by cxnvass** [Xinyuan-LilyGO/LilyGo-Camera-Series#17]
I'm using the sketch is the example with the T-SIMCAM and I keep having this error:

A fatal error occurred: Could not open COM6, the port doesn't exist

also another question, what board should I use in the board manager? I can't find the exact one for the T-SIMCAM.

**Comment by lewisxhe** [comment]
Press and hold the BOOT button (don't let go), then insert it into the USB, and then click upload to try

**Comment by cxnvass** [comment]
>
