### ISSUE TITLE
The choose of debugger for T-SIMCAM

### ISSUE THREAD

**Issue by EvanChristan123** [Xinyuan-LilyGO/LilyGo-Camera-Series#37]
Hi there, I would like to ask whether there is a debugger suitable for the T-SIMCAM. Is J-LINK a suitable debugger for debugging T-SIMCAM? Or any other available options?

**Comment by lewisxhe** [comment]
https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-guides/usb-serial-jtag-console.html
