### ISSUE TITLE
How to use the device with arduino IDE

### ISSUE THREAD

**Issue by anthonyhoegberg** [Xinyuan-LilyGO/LilyGo-Camera-Series#40]
My company is currently considering using this device and im the developer in charge to test different devices and see what meets our expectations. Currently we are testing T-SIMCAM with a PCIE sim module to take pictures and send the data to our servers.

Is there some example code or tutorial to use the device with the arduino ide, or is it just default settings overall?
If not, Im wondering about what settings and etc to get the device working and what libraries if necessary that might be needed to get it to work with the arduino ide.

Any help would be greatly helpful. Thanks.

**Comment by quinquerin** [comment]
![image_2024-05-30_183128749](https://github.com/Xinyuan-LilyGO/LilyGo-Camera-Series/assets/169747315/fcd291bf-a928-4f9d-8893-1f86192db32e)
