### ISSUE TITLE
Schematic error in T_SIMCAM-V1.0 board

### ISSUE THREAD

**Issue by jasenk2** [Xinyuan-LilyGO/LilyGo-Camera-Series#7]
There is serious schematic error on this board, which preventing PCIE modem to be powered when board operate from battery.
The transistor Q1,Q2( NCE3401PI) is opened only when gate there is powered by USB port, this way it preventing power

**Comment by lbuque** [comment]
When only using battery, you need to set PWR_EN Pin to high level to power on the PCIE modem.
