### ISSUE TITLE
How to upload sketch from Arduino IDE to T-SimCam

### ISSUE THREAD

**Issue by eloquentarduino** [Xinyuan-LilyGO/LilyGo-Camera-Series#8]
I bought a T-SimCam. How do I upload a sketch from the Arduino IDE?
Simply hitting upload doesn't work.
Do I need to press RST or BOOT buttons in any given sequence?
I have the Lilygo USB to TTL device.

**Comment by lbuque** [comment]
The pc is directly connected to the t-simcam via usb.

rIf it cannot be downloaded automatically, you need to manually enter the download mode. (This operation is the same as other esp32 chips)

**Comment by eloquentarduino** [comment]
Can you please describe step by step what I have to do?

**Comment by lbuque** [comment]
The following configuration is recommended:

![image](https://user-images.githubusercontent.com/46518962/204067384-73d26ed4-d92a-486c-9a66-9e9245b42e00.png)

**Comment by eloquentarduino** [comment]
I was able to upload a sketch only once. Now it throws error while uploading.

```
Chip is ESP32-S3
Features: WiFi, BLE
Crystal is 40MHz
MAC: 68:b6:b3:21:a6:5c
Uploading stub...
Running stub...
Stub running...
Configuring flash size...
Error with exit status 1
```

**Comment by abratchik** [comment]
Just released a new version of [esp32-web-server](https://github.com/abratchik/esp32-cam-webserver), you may test with this board. Working great for me so far, thanks a lot!

**Comment by RogerParkinson** [comment]
Did this actually get resolved or just closed? Questions I have:

- Was there some sequence of buttons that needs pressing? 
- Did the problem with uploading the sketch which then threw errors get resolved?

**Comment by RogerParkinson** [comment]
Okay for the next guy, I have it working now. I did not have to press any buttons. I just needed these settings
![image](https://github.com/Xinyuan-LilyGO/LilyGo-Camera-Series/assets/3478501/67b532f3-9921-432b-a51f-53b19b3b97ee)
This is using the sketch at examples/sketch
