### ISSUE TITLE
T-SimCam / SIM7600E Module

### ISSUE THREAD

**Issue by Rudolf10000** [Xinyuan-LilyGO/LilyGo-Camera-Series#9]
Hi, 
I bought a T-SimCam and a pcie sim 7600e module.

After hours i found this Arduino IDE settings:
[Settings](https://github.com/Xinyuan-LilyGO/LilyGo-Camera-Series/issues/8#topl)
Then I sucessfully flashed the "Sketch" via Arduino IDE 2.0.2
[Sketch](https://github.com/Xinyuan-LilyGO/LilyGo-Camera-Series/tree/master/examples/sketch)
But how to implement the SIM ?
Is there someone , who could make all components work together ?
I could not find examples or tutorials.
While fishing in the dark, i already destroyed the onboard usb of the SimCam.
Could pls. someone put me on the trail ?

**Comment by lbuque** [comment]
You can refer to the code of [examples/pic2cloud](https://github.com/Xinyuan-LilyGO/LilyGo-Camera-Series/tree/master/examples/pic2cloud).

**Comment by medir** [comment]
Hi,
Just a day ago they published the factory code that I think it could be useful for you: [/examples/T-SIMCAM-FACTORY](https://github.com/Xinyuan-LilyGO/LilyGo-Camera-Series/tree/master/examples/T-SIMCAM-FACTORY)

**Comment by Rudolf10000** [comment]
Thanks a lot. I could make it run using a combination of 
[[/examples/T-SIMCAM-FACTORY](https://github.com/Xinyuan-LilyGO/LilyGo-Camera-Series/tree/master/examples/T-SIMCAM-FACTORY)]
[https://github.com/abratchik/esp32-cam-webserver](url)
and 
[[examples/SIM7600/TinyGSM_Allfunctions](https://github.com/Xinyuan-LilyGO/LilyGo-T-PCIE/tree/master/examples/SIM7600/TinyGSM_Allfunctions)]
Now i struggle with the battery . When i connect the battery, nothing happens.
But that is another new issue.
Thank you again.
